# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/templates/opinionated-solution/"
    schedule:
      interval: "daily"
    groups:
      roslynator:
        patterns:
          - "Roslynator*"
      ms-codeanalysis:
        patterns:
          - "Microsoft.CodeAnalysis*"
      benchmark-dotnet:
        patterns:
          - "BenchmarkDotNet*"
      entityframework-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      hangfire:
        patterns:
          - "Hangfire*"
      serilog:
        patterns:
          - "Serilog*"
      xunit:
        patterns:
          - "xunit*"
      fakeiteasy:
        patterns:
          - "FakeItEasy*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/templates/opinionated-solution/"
    schedule:
      interval: "weekly"
