# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "nuget"
    directory: "/templates/opinionated-solution/"
    schedule:
      interval: "daily"
    groups:
      roslynator:
        patterns:
          - "Roslynator*"
      ms-codeanalysis:
        patterns:
          - "Microsoft.CodeAnalysis*"
      benchmark-dotnet:
        patterns:
          - "BenchmarkDotNet*"
      entityframework-core:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      aspnetcore:
        patterns:
          - "Microsoft.AspNetCore*"
      hangfire:
        patterns:
          - "Hangfire*"
      serilog:
        patterns:
          - "Serilog*"
      xunit:
        patterns:
          - "xunit*"
      fakeiteasy:
        patterns:
          - "FakeItEasy*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/templates/opinionated-solution/.github/workflows/" # This needs to be specified as a full path since "/" has some special handling: https://github.com/dependabot/dependabot-core/blob/96509eb5076846056604aee7e62fb155134e4090/github_actions/lib/dependabot/github_actions/file_fetcher.rb#L36
    schedule:
      interval: "daily"
