changelog:
  categories:
    - title: ":shipit: Pull requests"
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: "📦 Dependency updates"
      labels:
        - dependencies
